<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WarehouseSystem2.Domain\WarehouseSystem2.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WarehouseSystem2.Data\WarehouseSystem2.Data.csproj" />
    <ProjectReference Include="..\WarehouseSystem2.Domain\WarehouseSystem2.Domain.csproj" />
  </ItemGroup>

</Project>
